# Generated by Django 4.2.16 on 2025-12-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HallBook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
    ]
