# Generated by Django 4.2.16 on 2025-12-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HallBook', '0002_rename_bookings_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=None, help_text='Required for communication', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='organization_name',
            field=models.CharField(blank=True, default=None, help_text='Optional: Name of the club or organization', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, default=None, help_text='Optional phone number', max_length=20, null=True),
        ),
    ]
