# Generated by Django 4.2.16 on 2025-12-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HallBook', '0003_remove_booking_contact_info_booking_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='no@gmail.com', help_text='Required for communication', max_length=254),
        ),
    ]
