# Generated by Django 4.2.16 on 2025-12-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HallBook', '0004_alter_booking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(help_text='Required for communication', max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Optional: Name of the club or organization', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional phone number', max_length=20, null=True),
        ),
    ]
