# Generated by Django 4.2.16 on 2025-12-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HallBook', '0005_alter_booking_email_alter_booking_organization_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='request_letter',
            field=models.FileField(blank=True, null=True, upload_to='request_letters/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='roll_number',
            field=models.CharField(default='079bel070', help_text='College Roll Number', max_length=20),
        ),
    ]
